### ISSUE TITLE
Please update "dailymotion" repo

### ISSUE THREAD

**Issue by mikeevstropov** [streamroot/videojs-hls.js#1]
I have same error: https://circleci.com/docs/git-npm-install

**Comment by AxelDelmas** [comment]
Thanks for filing this issue. This should be fixed now, can you try again?

**Comment by mikeevstropov** [comment]
@AxelDelmas Sorry, friend. I think problem on my side. I have different errors when i try to build...
Tell me please, if i put vjs-hls.js file after videojs and hls.js it will be work in theory?
