### ISSUE TITLE
Video doesn't start in IE11

### ISSUE THREAD

**Issue by marnusw** [streamroot/videojs-hls.js#10]
This lib works great for me in all browsers except IE11. In the network log I can see the `m3u8` manifest is loaded, and then the first `.ts` shows up as well but apparently doesn't continue loading. The `video.js` player shows the controls and hides the poster as if it's ready to start playing the video, but total time is shown as zero and nothing happens.

If I just swap out `videojs-hls.js` for `videojs-contrib-hls` it works fine in IE11, but I find `hls.js` is better overall in other browsers, so I would really like for this lib to work in IE11 as well.

Do you have any idea what the problem might be?

**Comment by marufactory2** [comment]
Try to change "enableWorker" option to "false".

**Comment by marnusw** [comment]
Brilliant, that worked! Thanks for the help @marufactory2.
