### ISSUE TITLE
Dist build

### ISSUE THREAD

**Issue by peterbe** [streamroot/videojs-hls.js#3]
The README says to use Grunt to build. 
What I need is a dist build, e.g. `dist/vjs-hls.min.js`

**Comment by rodincave** [comment]
Do you mean you want a minified build version?

**Comment by peterbe** [comment]
I want to get a minified build version, yes. I appreciate if you don't want to include this into the git repo, but I was hoping I'd be able to do something like `grunt build` and it'd exit and then I'd be able to do `cp dist/videojs-hls.min.js /some/other/project/libs/`

**Comment by AxelDelmas** [comment]
Just merged #4. You can now run `grunt build` and then `cp dist/vjs-hls.js /some/other/project/libs/`
